server:
  port: 6565

spring:
  application:
    name: sc-server-configuration
  profiles:
    active: default


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

